# Preprocesamiento de datos

En este cuaderno limpiaremos los datos que hemos obtenido haciendo webscrapping.

Primero importamos librerías.

In [1]:
import pandas as pd
import numpy as np

Cargamos los datos.

In [3]:
# Carga el archivo CSV omitiendo las dos primeras filas problemáticas.
data = pd.read_csv('../data/datos_completos_exogenos_ibex35.csv')

data.head()

,Price,IBEX35_AdjClose,IBEX35_Close,IBEX35_High,IBEX35_Low,IBEX35_Open,IBEX35_Volume,S&P500_AdjClose,S&P500_Close,S&P500_High,...,Petroleo_High,Petroleo_Low,Petroleo_Open,Petroleo_Volume,EUR/USD_AdjClose,EUR/USD_Close,EUR/USD_High,EUR/USD_Low,EUR/USD_Open,EUR/USD_Volume
0,Ticker,^IBEX,^IBEX,^IBEX,^IBEX,^IBEX,^IBEX,^GSPC,^GSPC,^GSPC,...,CL=F,CL=F,CL=F,CL=F,EURUSD=X,EURUSD=X,EURUSD=X,EURUSD=X,EURUSD=X,EURUSD=X
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-01-03 00:00:00+00:00,8732.3916015625,8732.400390625,8743.2998046875,8597.099609375,8739.2001953125,186689000,1277.06005859375,1277.06005859375,1284.6199951171875,...,103.18000030517578,99.6500015258789,99.69999694824219,275481,1.2940963506698608,1.2940963506698608,1.3065917491912842,1.2936275005340576,1.2936275005340576,0
3,2012-01-04 00:00:00+00:00,8581.791015625,8581.7998046875,8701.2998046875,8526.7998046875,8683.400390625,243803000,1277.300048828125,1277.300048828125,1278.72998046875,...,103.73999786376953,101.87999725341797,102.98999786376953,271711,1.3056023120880127,1.3056023120880127,1.3073946237564087,1.2902060747146606,1.305397868156433,0
4,2012-01-05 00:00:00+00:00,8329.5908203125,8329.599609375,8598.7001953125,8301.2001953125,8598.7001953125,192704000,1281.06005859375,1281.06005859375,1283.050048828125,...,103.7300033569336,101.30000305175781,103.29000091552734,295615,1.2931424379348755,1.2931424379348755,1.2942973375320435,1.2785271406173706,1.2930923700332642,0

Renombramos las columnas para que coincidan con sus valores.

In [4]:
# Renombra las columnas para que tengan sentido.
data = data.rename(columns={'Price': 'Date'})
data.head()

,Date,IBEX35_AdjClose,IBEX35_Close,IBEX35_High,IBEX35_Low,IBEX35_Open,IBEX35_Volume,S&P500_AdjClose,S&P500_Close,S&P500_High,...,Petroleo_High,Petroleo_Low,Petroleo_Open,Petroleo_Volume,EUR/USD_AdjClose,EUR/USD_Close,EUR/USD_High,EUR/USD_Low,EUR/USD_Open,EUR/USD_Volume
0,Ticker,^IBEX,^IBEX,^IBEX,^IBEX,^IBEX,^IBEX,^GSPC,^GSPC,^GSPC,...,CL=F,CL=F,CL=F,CL=F,EURUSD=X,EURUSD=X,EURUSD=X,EURUSD=X,EURUSD=X,EURUSD=X
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-01-03 00:00:00+00:00,8732.3916015625,8732.400390625,8743.2998046875,8597.099609375,8739.2001953125,186689000,1277.06005859375,1277.06005859375,1284.6199951171875,...,103.18000030517578,99.6500015258789,99.69999694824219,275481,1.2940963506698608,1.2940963506698608,1.3065917491912842,1.2936275005340576,1.2936275005340576,0
3,2012-01-04 00:00:00+00:00,8581.791015625,8581.7998046875,8701.2998046875,8526.7998046875,8683.400390625,243803000,1277.300048828125,1277.300048828125,1278.72998046875,...,103.73999786376953,101.87999725341797,102.98999786376953,271711,1.3056023120880127,1.3056023120880127,1.3073946237564087,1.2902060747146606,1.305397868156433,0
4,2012-01-05 00:00:00+00:00,8329.5908203125,8329.599609375,8598.7001953125,8301.2001953125,8598.7001953125,192704000,1281.06005859375,1281.06005859375,1283.050048828125,...,103.7300033569336,101.30000305175781,103.29000091552734,295615,1.2931424379348755,1.2931424379348755,1.2942973375320435,1.2785271406173706,1.2930923700332642,0

In [5]:
# Eliminar las primeras dos filas usando .drop()
data = data.drop([0, 1]).reset_index(drop=True)

data.head()

,Date,IBEX35_AdjClose,IBEX35_Close,IBEX35_High,IBEX35_Low,IBEX35_Open,IBEX35_Volume,S&P500_AdjClose,S&P500_Close,S&P500_High,...,Petroleo_High,Petroleo_Low,Petroleo_Open,Petroleo_Volume,EUR/USD_AdjClose,EUR/USD_Close,EUR/USD_High,EUR/USD_Low,EUR/USD_Open,EUR/USD_Volume
0,2012-01-03 00:00:00+00:00,8732.3916015625,8732.400390625,8743.2998046875,8597.099609375,8739.2001953125,186689000,1277.06005859375,1277.06005859375,1284.6199951171875,...,103.18000030517578,99.6500015258789,99.69999694824219,275481,1.2940963506698608,1.2940963506698608,1.3065917491912842,1.2936275005340576,1.2936275005340576,0
1,2012-01-04 00:00:00+00:00,8581.791015625,8581.7998046875,8701.2998046875,8526.7998046875,8683.400390625,243803000,1277.300048828125,1277.300048828125,1278.72998046875,...,103.73999786376953,101.87999725341797,102.98999786376953,271711,1.3056023120880127,1.3056023120880127,1.3073946237564087,1.2902060747146606,1.305397868156433,0
2,2012-01-05 00:00:00+00:00,8329.5908203125,8329.599609375,8598.7001953125,8301.2001953125,8598.7001953125,192704000,1281.06005859375,1281.06005859375,1283.050048828125,...,103.7300033569336,101.30000305175781,103.29000091552734,295615,1.2931424379348755,1.2931424379348755,1.2942973375320435,1.2785271406173706,1.2930923700332642,0
3,2012-01-06 00:00:00+00:00,8289.0908203125,8289.099609375,8445.900390625,8233.7998046875,8369.7001953125,153765000,1277.81005859375,1277.81005859375,1281.8399658203125,...,102.80000305175781,100.87999725341797,101.3499984741211,290458,1.279606819152832,1.279606819152832,1.281295657157898,1.270405888557434,1.2792959213256836,0
4,2012-01-09 00:00:00+00:00,8278.8916015625,8278.900390625,8404.400390625,8250.099609375,8314.5,173948000,1280.699951171875,1280.699951171875,1281.989990234375,...,102.1500015258789,100.0999984741211,101.91999816894531,311866,1.2680377960205078,1.2680377960205078,1.2784944772720337,1.2679574489593506,1.2679574489593506,0

Vemos los tipos de datos.

In [6]:
data.dtypes

Date                     object
IBEX35_AdjClose          object
IBEX35_Close             object
IBEX35_High              object
IBEX35_Low               object
IBEX35_Open              object
IBEX35_Volume            object
S&P500_AdjClose          object
S&P500_Close             object
S&P500_High              object
S&P500_Low               object
S&P500_Open              object
S&P500_Volume            object
Petróleo WTI_AdjClose    object
Petroleo_Close           object
Petroleo_High            object
Petroleo_Low             object
Petroleo_Open            object
Petroleo_Volume          object
EUR/USD_AdjClose         object
EUR/USD_Close            object
EUR/USD_High             object
EUR/USD_Low              object
EUR/USD_Open             object
EUR/USD_Volume           object
dtype: object

Convertimos la columna `Date` a objeto datetime y la convertimos en el índice del DataFrame, una práctica común para hacer series temporales. Además eliminamos la hora de la fecha ya que no es relevante.

In [7]:
# Convertimos la columna 'Date' en un índice de fecha
data['Date'] = pd.to_datetime(data['Date'])
data['Date'] = data['Date'].dt.date  # Extrae solo la fecha (sin horas)
data.set_index('Date', inplace=True)

data.head()

,IBEX35_AdjClose,IBEX35_Close,IBEX35_High,IBEX35_Low,IBEX35_Open,IBEX35_Volume,S&P500_AdjClose,S&P500_Close,S&P500_High,S&P500_Low,...,Petroleo_High,Petroleo_Low,Petroleo_Open,Petroleo_Volume,EUR/USD_AdjClose,EUR/USD_Close,EUR/USD_High,EUR/USD_Low,EUR/USD_Open,EUR/USD_Volume
Date,,,,,,,,,,,,,,,,,,,,,
2012-01-03,8732.3916015625,8732.400390625,8743.2998046875,8597.099609375,8739.2001953125,186689000,1277.06005859375,1277.06005859375,1284.6199951171875,1258.8599853515625,...,103.18000030517578,99.6500015258789,99.69999694824219,275481,1.2940963506698608,1.2940963506698608,1.3065917491912842,1.2936275005340576,1.2936275005340576,0
2012-01-04,8581.791015625,8581.7998046875,8701.2998046875,8526.7998046875,8683.400390625,243803000,1277.300048828125,1277.300048828125,1278.72998046875,1268.0999755859375,...,103.73999786376953,101.87999725341797,102.98999786376953,271711,1.3056023120880127,1.3056023120880127,1.3073946237564087,1.2902060747146606,1.305397868156433,0
2012-01-05,8329.5908203125,8329.599609375,8598.7001953125,8301.2001953125,8598.7001953125,192704000,1281.06005859375,1281.06005859375,1283.050048828125,1265.260009765625,...,103.7300033569336,101.30000305175781,103.29000091552734,295615,1.2931424379348755,1.2931424379348755,1.2942973375320435,1.2785271406173706,1.2930923700332642,0
2012-01-06,8289.0908203125,8289.099609375,8445.900390625,8233.7998046875,8369.7001953125,153765000,1277.81005859375,1277.81005859375,1281.8399658203125,1273.3399658203125,...,102.80000305175781,100.87999725341797,101.3499984741211,290458,1.279606819152832,1.279606819152832,1.281295657157898,1.270405888557434,1.2792959213256836,0
2012-01-09,8278.8916015625,8278.900390625,8404.400390625,8250.099609375,8314.5,173948000,1280.699951171875,1280.699951171875,1281.989990234375,1274.550048828125,...,102.1500015258789,100.0999984741211,101.91999816894531,311866,1.2680377960205078,1.2680377960205078,1.2784944772720337,1.2679574489593506,1.2679574489593506,0

Vemos si hay datos nulos.

In [8]:
data.isnull().sum()

IBEX35_AdjClose          0
IBEX35_Close             0
IBEX35_High              0
IBEX35_Low               0
IBEX35_Open              0
IBEX35_Volume            0
S&P500_AdjClose          0
S&P500_Close             0
S&P500_High              0
S&P500_Low               0
S&P500_Open              0
S&P500_Volume            0
Petróleo WTI_AdjClose    0
Petroleo_Close           0
Petroleo_High            0
Petroleo_Low             0
Petroleo_Open            0
Petroleo_Volume          0
EUR/USD_AdjClose         0
EUR/USD_Close            0
EUR/USD_High             0
EUR/USD_Low              0
EUR/USD_Open             0
EUR/USD_Volume           0
dtype: int64

Aseguramos que no haya habido errores al importar los datos y que no haya duplicados.

In [9]:
data.duplicated().sum()

0

Consideramos una columna clave `Adj Close` ya que es útil para un análisis a largo plazo porque muestra el valor real, considerando los dividendos y otras operaciones corporativas.

Ahora que el análisis ha terminado, exportamos los datos limpios.

In [10]:
data.to_csv('../data/datos_completos_exogenos_limpio.csv')